### ISSUE TITLE
No module named 'scenes.main_scene'

### ISSUE THREAD

**Issue by shiipou** [antomarsi/RasPipBoy3000-MK4#1]
Hello,

I've try to run your pipboy project, but I encounter an error :
```
No module named 'scenes.main_scene'
```

Did you have an Idea ?

I see you haven't the `main_scene.py` file on the directory `scenes/` did you forget to push it ?

**Comment by antomarsi** [comment]
yeah, i was trying to change stuffs a little, and pushed a incompleted commit, i will try to fix it.
You can also use the `3f9fd3b660be15d4c21311e078e90607f643445b` commit, it will compile.
Just to know, the project is far from finished, but you can have a idea on how to work with pygame.

**Comment by shiipou** [comment]
Ok, thank you

I'll check it

**Comment by Chest1** [comment]
Good first isdue
